
OBJS=lexer.o parser.tab.o filtered.o
CFLAGS=-g

parser: $(OBJS)
	$(CC) -o$@ $(OBJS)

lexer: lexer.o
	$(CC) -o$@ $< -lfl

parser.tab.h: parser.y
	bison -d $<

parser.tab.c: parser.y
	bison -d $<

lexer.c: lexer.l parser.tab.h
	flex -o$@ $<

lexer.o: lexer.c
	$(CC) -c $<

